Decorate
V0pe/School-library pull request #2
Opened 2022-07-19 16:45 UTC by V0pe

### Pattern Decoration

- [ ] Add the base class
- [ ] Add the base decorator
- [ ] Add the pattern decorator

2022-07-19 16:54 UTC, Kingstalux requested changes
Hi @V0pe, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![175083599-879bf673-fb93-406f-939c-de7e586bf6d9](https://user-images.githubusercontent.com/85113567/179806506-563ee6d3-e23c-44d8-82f6-07790904e510.gif)

## Highlights 👏 
✅ Linters are passing 👌 
✅ Good commit history 👍 
✅ Correct Gitflow used 👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-19 16:54 UTC, Kingstalux commented on decorator.rb
>      end
- [ ] Good job so far 👍 Kindly add the `attr_accessor :nameable` to your `Decorator` class 😄

2022-07-19 16:54 UTC, Kingstalux commented on decorator.rb
> +  end
- [ ] You are to capitalize the first letter of the given name but your method capitalizes the whole name. Kindly rectify this issue 👍

2022-07-19 17:01 UTC, V0pe commented on decorator.rb
>      end
I added but removed because it didnt affect result

2022-07-19 17:02 UTC, V0pe commented on decorator.rb
> +  end
@Kingstalux my bad. I thought it was uppercase all. Thanks 👍

2022-07-19 17:18 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED 🍾✔🎉**
Hello @V0pe 👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- You documented your work professionally.✔
- Github inline comments feature is used properly.
- You asked for changes in a polite and friendly way.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-20 05:59 UTC, V0pe commented
@emmanuellekamwa Merci.

2022-07-20 05:59 UTC, merged